# Generated by Django 5.1.15 on 2026-07-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('trade_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('handover', '물건 인계'), ('trade', '대면 거래')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('manual', '수동확인')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_verifications', to='marketplace.chatroom')),
                ('verifier_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_as_a', to=settings.AUTH_USER_MODEL)),
                ('verifier_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hop_index', models.PositiveSmallIntegerField()),
                ('side', models.CharField(choices=[('give', '인계'), ('receive', '인수')], max_length=10)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_steps', to='marketplace.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BluetoothVerification',
        ),
        migrations.AddConstraint(
            model_name='verificationstep',
            constraint=models.UniqueConstraint(fields=('chatroom', 'hop_index', 'side'), name='unique_verification_step'),
        ),
    ]
