# Generated by Django 5.1.15 on 2026-07-24 07:46

from django.db import migrations, models


def migrate_agent_role_forward(apps, schema_editor):
    """기존 'agent'는 전부 구매자 쪽에서 초대한 것이었으므로 buyer_agent로 옮긴다
    (판매자 대리인 초대는 이번에 처음 생기는 기능이라 과거 데이터에는 없다)."""
    ChatParticipant = apps.get_model('marketplace', 'ChatParticipant')
    ChatParticipant.objects.filter(role='agent').update(role='buyer_agent')


def migrate_agent_role_backward(apps, schema_editor):
    ChatParticipant = apps.get_model('marketplace', 'ChatParticipant')
    ChatParticipant.objects.filter(role__in=['seller_agent', 'buyer_agent']).update(role='agent')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_notification'),
    ]

    operations = [
        migrations.RunPython(migrate_agent_role_forward, migrate_agent_role_backward),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('buyer', '구매자'), ('seller', '판매자'), ('seller_agent', '판매자 대리인'), ('buyer_agent', '구매자 대리인')], max_length=20),
        ),
    ]
